<footer class="shadow-lg p-3 mb-5 bg-black rounded">
    <div align="center">
        <blockquote class="blockquote text-right">
            <p class="mb-0">"We wanted to perfect user choice so I asked them to create opportunity..."</p>
            <p>Creative director of BSH Production <cite title="Source Title">Washington Post</cite><p>

        </blockquote>
        <form name="form" action="FrontController" method="POST">
            <input type="hidden" name="taget" value="tologin">
            <input type="submit" value="Employee login Page" class="btn btn-dark btn-lg">
        </form>
    </div>
</footer>
</html>