<footer class="shadow-lg p-3 mb-5 bg-black rounded">
    <div align="center">
        <blockquote class="blockquote text-right">
            <p class="mb-0">"We wanted to perfect user choice so I asked them to create opportunity..."</p>
            <p>Creative director of BSH Production <cite title="Source Title">Washington Post</cite><p>

        </blockquote>
        <input type="submit" value="Employee login Page" class="btn btn-dark btn-lg">
    </div>
</footer>
</html>